### PR TITLE
Make sure the provided default function is always called when packing

### PR DESCRIPTION
**Pull request by pramukta**
This is to address issue #133.  All the tests pass with both the cython and fallback versions.  (I think, am not 100% clear on the cython workflow).  Let me know if there is anything wrong or that should be better or if I'm off base about anything.

### CODE REVIEW

**Comment by pramukta** [comment]
Based on the CI it looks like I didn't address python 3.  Looking into it.

**Comment by pramukta** [comment]
Ok, looks like it's good to go.  Let me know if there's anything else I should do.

**Comment by methane** [comment]
I'm sorry, but I will not merge this breaking API change.
`default` keyword argument comes from [here](https://docs.python.org/3.3/library/json.html#json.dump).

Please consider about existing code like below:

```python
def default(obj):
    if isinstance(obj, datetime):
        return obj.timestamp()
    raise TypeError("Unsupported type %s" % (type(obj),))
```

**Comment by methane** [comment]
I think it's OK to call `default` only when integer overflow.

I'll drop Python 2.6 support when msgpack-python 0.5.
It is easy to check overflow with this API.
https://docs.python.org/2.7/c-api/long.html#c.PyLong_AsLongLongAndOverflow

**Comment by pramukta** [comment]
Ah I see, good to know where that API came from.  I had assumed that it was supposed to be used the way it was documented [here](https://github.com/msgpack/msgpack-python/blob/master/README.rst#packingunpacking-of-custom-data-type).  It might be a good idea to update those docs to match the test you posted.  In the mean time, I'll see if I can implement it closer to the way you've suggested.

**Comment by pramukta** [comment]
Closing in favor of the alternate implementation #135

**Pull request closed without merging**
