### PR TITLE
Add hypothesis-powered tests

### PR DESCRIPTION
**Pull request by hexagonrecursion**
This works towards https://github.com/msgpack/msgpack-python/issues/219
See https://google.github.io/oss-fuzz/getting-started/new-project-guide/python-lang/#hypothesis

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
This is wrong. It should not be that hard to add a new dependency. Why are you repeating the same information in so many places? You have tox.ini. Use it.

**Comment by methane** [comment]
I do not use tox.

**Comment by hexagonrecursion** [comment]
I have finally hit genuine test failures. I'll look into them later.
```
>       assert repr(obj) == repr(got)

E       assert '{b\'"b\': No...641537: None}' == '{2.000000001...\'"b\': None}'

E         - {2.0000000011641537: None, b'"b': None}

E         + {b'"b': None, 2.0000000011641537: None}
```

**Comment by methane** [comment]
> I have finally hit genuine test failures. I'll look into them later.

Dicts in old Pythons don't preserve order.

**Comment by methane** [comment]
I'm not interested in fuzzing packer. I'm interested in Unpacker because it can be attack surface.

**Pull request closed without merging**
