### PR TITLE
Unpacker reset

### PR DESCRIPTION
**Pull request by hendrik-cliqz**
see #144

### CODE REVIEW

**Comment by methane** [comment]
Unpacker takes file-like object in constructor.
This PR doesn't care about it.

**Comment by hendrik-cliqz** [comment]
You are right. As I do not use it with a file-like object I simply overlooked this usecase.

But I am wondering about the way to handle it: It seems to me that reset does not make sense if it reads from a file-like object. So I would throw as in feed(). Correct?

**Comment by methane** [comment]
What is motivation of reset?
Is it really unrelated to file-like object usage?

**Comment by hendrik-cliqz** [comment]
sorry for the late reply. I am using the reset method in a RPC library - so essentially sending msgpack over the network:

https://github.com/hendrik-cliqz/mprpc/blob/master/mprpc/client.pyx#L137

The unpacker object in there is reused, to ensure it is ok to use it, I reset it. I want to avoid re-creating the object for every call due to perf reasons.

**Comment by methane** [comment]
OK.  So, why `unpacker.feed(file=None)` doesn't make sense?

**Comment by hendrik-cliqz** [comment]
sorry, I do not get the question. "unpacker.feed(file=None)" isn't a valid call, is it?

Actually I do not need this PR anymore, so I suggest to close it.

**Comment by methane** [comment]
OK.  Thanks anyway.

**Pull request closed without merging**
