### PR TITLE
Use struct.unpack_from instead of struct.unpack

### PR DESCRIPTION
**Pull request by methane**
It can avoid unnecessary slice.
And use bytearray as buffer since overhead is acceptable now.

### CODE REVIEW

**Comment by methane** [comment]
## PyPy 5.1.1

master:

```
unpacking integers (fallback)    0.134460, 0.084203, 0.084150, 0.086851
unpacking bytes (fallback)       0.143169, 0.076271, 0.076101, 0.076042
unpacking lists (fallback)       1.410900, 1.307060, 1.315248, 1.304037
unpacking dicts (fallback)       1.098686, 1.023390, 1.023976, 1.016101
```

unpack-from:

```
unpacking integers (fallback)    0.172767, 0.119486, 0.124878, 0.121022
unpacking bytes (fallback)       0.470616, 0.341301, 0.343614, 0.339794
unpacking lists (fallback)       1.575918, 1.470916, 1.467804, 1.470707
unpacking dicts (fallback)       1.269204, 1.115627, 1.120089, 1.119013
```

**Comment by methane** [comment]
## CPython 3.5.1

master:

```
unpacking integers (fallback)  22.679333, 22.677238, 22.690126, 22.673825
unpacking bytes (fallback)       5.232754, 5.213763, 5.215992, 5.227349
unpacking lists (fallback)     30.811691, 30.898622, 31.056381, 30.862766
unpacking dicts (fallback)     33.459914, 33.809303, 33.761068, 34.080613
```

unpack-from:

```
unpacking integers (fallback)  20.481262, 20.493314, 20.485122, 20.477774
unpacking bytes (fallback)       5.765638, 5.781167, 5.764243, 5.766404
unpacking lists (fallback)     27.857848, 27.837129, 27.907444, 27.795069
unpacking dicts (fallback)     31.258448, 31.380827, 31.441959, 32.189954
```

**Comment by jfolz** [comment]
Are these numbers obtained with the new benchmark?

About the buffer: maybe pre-allocate it and grow as necessary, similar to C code?

**Comment by methane** [comment]
> Are these numbers obtained with the new benchmark?

No.  Current benchmark.  So PyPy may or may not optimize out some code in master branch.

> About the buffer: maybe pre-allocate it and grow as necessary, similar to C code?

bytearray should do overallocate.  I don't want to make unpacker complicated for double overallocate.

**Pull request merged**
