### PR TITLE
Added Python 3.5 to the build matrix

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Seems that everything is in order. Please merge.

**Comment by ThomasWaldmann** [comment]
Looks good.

What's the effect of the line 5 change?

**Comment by thedrow** [comment]
Tox will run under 3.5. Travis doesn't have it preinstalled so you have to use it in order for travis to download it.

**Comment by methane** [comment]
thanks

**Comment by thedrow** [comment]
Sure no problem.

**Pull request merged**
