### PR TITLE
Remove code and tests for unsupported Python 2.6, 3.3 and 3.4

### PR DESCRIPTION
**Pull request by hugovk**
https://github.com/msgpack/msgpack-python/pull/248/commits/c11bb640d8380f0a8ae080e17398f10e81d94c71 says:

> Python 3.3 and 3.4 will not be supported officially in next minor version

And 2.6 was dropped in https://github.com/msgpack/msgpack-python/pull/168.

This removes some 2.6, 3.3 and 3.4 stuff.

Also remove this restriction form .travis.yml to allow me to test this feature branch before creating the PR:
```yml
-branches:		
-  only:		
-    - master		
-
```
I think this is a good thing to keep, but let me know if you'd like it putting back.

Also ignore .cache directory, created from build/test.

### CODE REVIEW

**Comment by hugovk** [comment]
The Docker CI failure also happens on master.

**Comment by methane** [comment]
I just want don't announce "Python 3.3 and 3.4 are supported."
Don't remove test until it make trouble.

**Comment by methane** [comment]
Removing code for 2.6 is nice.

**Comment by hugovk** [comment]
Please see https://github.com/msgpack/msgpack-python/pull/250.

**Comment by hugovk** [comment]
Merge conflict resolved.

**Comment by hugovk** [comment]
By the way, here's the pip installs for msgpack-python from PyPI for the last month:
```
$ pypinfo --percent --pip msgpack-python pyversion
python_version percent download_count
-------------- ------- --------------
2.7              83.9%        669,038
3.6               6.6%         52,967
3.5               6.2%         49,744
3.4               2.9%         22,903
2.6               0.2%          1,980
3.3               0.1%            484
3.7               0.0%            278
None              0.0%              6
3.2               0.0%              3
3.1               0.0%              1

```
This shows Python 2.6 and 3.3 have very little usage.

**Comment by methane** [comment]
OK, simplifying `appveyor.yml` looks nice.

**Comment by methane** [comment]
thanks

**Pull request merged**
